### ISSUE TITLE
Multiple typos in Part 8.1

### ISSUE THREAD

**Issue by imbrandonj** [rage/programming-22#21]
"If you haven't use Visual Studio Code before, you will find the installation instructions..."
'use' should be 'used'

"In programming, the term has the specific meaning of an independent whole whi, in this case containing some bits of data..."
'whi' - not sure what that should be.

"The way to distuinguish methods from other functions is the way..."
distinguish*

**Comment by jussmaki** [comment]
Fixed. Thank you! :)
