### ISSUE TITLE
A typo in Part 6 in the example of exercise 09 - city bikes.

### ISSUE THREAD

**Issue by myathtunkhant** [rage/programming-22#35]
In Part 6, exercise 9, City Bikes, the example output for "Part 1:Distance between stations" contains a typo of the variable name. The previous code includes a line "d = distance(stations, "Designmuseo", "Hietalahdentori")", but the sample output has the text "print(e)"
which is different a variable name.  The full example is below:

stations = get_station_data('stations1.csv')
d = distance(stations, "Designmuseo", "Hietalahdentori")
print(e)
d = distance(stations, "Viiskulma", "Kaivopuisto")
print(e)

**Comment by jussmaki** [comment]
Fixed. Thank you! :)
