### ISSUE TITLE
Bad wording in Part 4 in the description of exercise 30

### ISSUE THREAD

**Issue by wolfing** [rage/programming-22#5]
In Part 4 exercise 30, the request text seems wrong. The text says "...The function **prints out** whichever of the strings is the shortest. If more than one are equally short, the function can **print out** any of the shortest strings".  
The function (as per the test requirements) shouldn't print out anything, but return the values, so I think it should read "...The function _returns_ whichever of" and "...the function can _return_ any of the ..."

**Comment by jussmaki** [comment]
Fixed. Thank you! :)
